[[IgnoredVulns]]
id = "GHSA-pq2g-wx69-c263"
ignoreUntil = 2025-04-01 # Optional exception expiry date
reason = "Awaiting release of fix from transient dependency"

[[IgnoredVulns]]
id = "GHSA-p53j-g8pw-4w5f"
ignoreUntil = 2025-10-01
reason = "Awaiting release of fix from transient dependency"

[[IgnoredVulns]]
id = "GHSA-j288-q9x7-2f5v"
reason = "Not critically affected"

[[IgnoredVulns]]
id = "GHSA-vc5p-v9hr-52mj"
reason = "Awaiting release of fix from transient dependency"
